# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586a78c024ce0f95c6db7104dfb1c14204ab85fa45df5326ab36a8aec80420e31ab16570bd4de9af7c736b347d0ac3faf40cb4f0deb9de2bd0b66f403f12a1cc

test:
  secret_key_base: 3725c5f99700bc2759b2b6b714b00d8e55df0a2a635485512d35245be5f902f6d4cedae0da08cc8808fa6b0412cd9b5e42a5919c483990dc4893b7ec648dbbd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
